src/Entity/Offer.php
<?php

namespace App\Entity;

use App\Repository\OfferRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=OfferRepository::class)
 */
class Offer
{

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column()
     * @Assert\NotBlank()
     * @Assert\Length(max=255)
     */
    private $title;

    /**
     * @ORM\Column(nullable=true)
     */
    private $location;

    /**
     * @ORM\ManyToOne(targetEntity=Profile::class)
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotNull()
     */
    private $profile;

    /**
     * @var OfferStatus
     *
     * @ORM\ManyToOne(targetEntity=OfferStatus::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $status;

    /**
     * @ORM\Column()
     * @Assert\NotBlank()
     * @Assert\Length(max=255)
     */
    private $client;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank()
     */
    private $requiredSkills;

    /**
     * @ORM\Column(type="date")
     * @Assert\NotNull()
     */
    private $startDate;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $desiredTechnologies;

    /**
     * @ORM\ManyToOne(targetEntity=Freelance::class, inversedBy="createdOffers")
     * @ORM\JoinColumn(nullable=false)
     */
    private $creator;

    /**
     * @ORM\OneToMany(targetEntity=PostulatedOffer::class, mappedBy="offer")
     * @Assert\NotNull()
     */
    private $applicants;

    public function __construct()
    {
        $this->startDate = new \DateTime("now");
        $this->applicants = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(?string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getProfile(): ?Profile
    {
        return $this->profile;
    }

    public function setProfile(?Profile $profile): self
    {
        $this->profile = $profile;

        return $this;
    }

    public function getStatus(): ?OfferStatus
    {
        return $this->status;
    }

    public function setStatus(?OfferStatus $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getClient(): ?string
    {
        return $this->client;
    }

    public function setClient(string $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getRequiredSkills(): ?string
    {
        return $this->requiredSkills;
    }

    public function setRequiredSkills(string $requiredSkills): self
    {
        $this->requiredSkills = $requiredSkills;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getDesiredTechnologies(): ?string
    {
        return $this->desiredTechnologies;
    }

    public function setDesiredTechnologies(?string $desiredTechnologies): self
    {
        $this->desiredTechnologies = $desiredTechnologies;

        return $this;
    }

    public function getCreator(): ?Freelance
    {
        return $this->creator;
    }

    public function setCreator(?Freelance $creator): self
    {
        $this->creator = $creator;

        return $this;
    }

    public function isCancel()
    {
        return $this->status->getTitle() === OfferStatus::CANCELED;
    }

    public function getColorStatus()
    {
        switch ($this->status->getTitle()) {
            case OfferStatus::APPLICANT:
                return 'primary';
            case OfferStatus::POSTULATED:
                return 'warning';
            case OfferStatus::ACCEPTED:
                return 'success';
            case OfferStatus::CANCELED:
                return 'danger';
            default:
                throw new \UnexpectedValueException('');
        }
    }

    /**
     * @return Collection|PostulatedOffer[]
     */
    public function getApplicants(): Collection
    {
        return $this->applicants;
    }

    public function addApplicant(PostulatedOffer $applicant): self
    {
        if (!$this->applicants->contains($applicant)) {
            $this->applicants[] = $applicant;
            $applicant->setOffer($this);
        }

        return $this;
    }

    public function removeApplicant(PostulatedOffer $applicant): self
    {
        if ($this->applicants->removeElement($applicant)) {
            // set the owning side to null (unless already changed)
            if ($applicant->getOffer() === $this) {
                $applicant->setOffer(null);
            }
        }

        return $this;
    }

    public function canBePostulated($user): bool
    {
        return ($this->status->getTitle() === OfferStatus::POSTULATED || $this->status->getTitle() === OfferStatus::APPLICANT) && $this->creator->getEmail() !== $user->getEmail();
    }

    public function containPostulatedOffer($postulatedOffer): bool
    {
        return !($this->getApplicants()->filter(function (PostulatedOffer $applicant) use ($postulatedOffer) {
            return $postulatedOffer->contains($applicant);
        })->isEmpty());

    }

    /**
     * @param int|null $userId
     *
     * @return bool
     */
    public function isCreator(?int $userId)
    {
        return $this->creator->getId() === $userId;
    }
}

templates/_header.html.twig
<header>
  <input type="checkbox" id="trigger_burger">
  <div class="container">
    <div class="row">
      <div class='col-8 col-lg-4  text-left siteLogo'>
        <span>{{ 'site.name'|trans }}</span>
      </div>
      <div class='d-flex d-lg-none col-4 text-right header__links burger__container headerRWD__menu'>
          <label for="trigger_burger" class="burger">
            <span class="burger__middleRow"></span>
          </label>
      </div>
      <div class='d-none d-lg-flex col-lg-8 text-right header__links'>
        <div class="header__menu">
          <a href="{{path('offer_list')}}">{{ 'header.see_offer'|trans }}</a>
          <a href="{{path('offer_add')}}">{{ 'header.submit_offer'|trans }}</a>
        </div>
        <div class="header__connexion">
          {% if app.user %}
          <a href="{{path('app_logout')}}">{{ 'account.logout'|trans }}</a>
          <a href="{{path('dashboard')}}" class="header__connexion--circled">{{ 'account.dashboard'|trans }}</a>
          {% else %}
          <a href="{{path('app_login')}}">{{ 'account.sign_in'|trans }}</a>
          <a href="{{path('register')}}" class="header__connexion--circled">{{ 'account.register'|trans }}</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
  <div class="d-flex d-lg-none col-md-6 col-sm-12 rwd_menu">
      <ul>
          <li class="text-center"><a href="{{path('offer_list')}}">{{ 'header.see_offer'|trans }}</a></li>
          <li class="text-center"><a href="{{path('offer_add')}}">{{ 'header.submit_offer'|trans }}</a></li>
        {% if app.user %}
          <li class="text-center"><a href="{{path('app_logout')}}">{{ 'account.logout'|trans }}</a></li>
          <li class="text-center"><a href="{{path('dashboard')}}" class="header__connexion--circled">{{ 'account.dashboard'|trans }}</a></li>
          {% else %}
          <li class="text-center"><a href="{{path('app_login')}}">{{ 'account.sign_in'|trans }}</a></li>
          <li class="text-center"><a href="{{path('register')}}" class="header__connexion--circled">{{ 'account.register'|trans }}</a></li>
          {% endif %}
      </ul>
  </div>
</header>

templates/base.html.twig
<!DOCTYPE html>
<html lang="{{ app.request.locale }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{{ asset( 'assets/favicon.png' ) }}" type="image/png"/>
    <title> {{ title|default('') }} - {{ 'site.name'|trans }}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.typekit.net/cwk8pui.css">

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <link href="{{ asset( 'assets/style.css' ) }}" rel="stylesheet">
    {% block stylesheets %}{% endblock %}
</head>
<body>
    <div class="bodySon">
    {% include '_header.html.twig' %}
    <main>
        <div class="container">
            {% block body %}{% endblock %}
        </div>
    </main>
</div>
{% block javascripts %}{% endblock %}
</body>
</html>

templates/dashboard.html.twig
{% extends 'base.html.twig' %}

{% set title = 'dashboard.label'|trans %}

{% block javascripts %}
    <script src="{{ asset('assets/js/jquery-3.5.1.min.js') }}"></script>
    <script>
        $(document).ready(function () {
            const $shows = $('div[id^=widget]');

            $('.show-item').click(function (e) {
                const widgetId = $(this).data('widget-id');
                const $widget = $('#widget-' + widgetId);

                $shows.each(function () {
                    if ($widget !== $(this)) {
                        $(this).slideUp()
                    }
                })

                if ($widget.css('display') === 'none') {
                    $widget.slideDown()
                } else {
                    $widget.slideUp()
                }
            })

            const $window = $(window)
            $(window).resize(function () {
                if ($window.width() > 992) {
                    $shows.each(function () {
                        $(this).slideDown()
                    })
                } else {
                    $shows.each(function () {
                        $(this).slideUp()
                    })
                }
            });

            $(window).resize()
        })
    </script>
{% endblock %}
{% set widget_counter = 0 %}

{% block body %}
    <div class="row">
        <div class="col border border-primary m-1">
            <div class="d-flex align-items-center justify-content-between">
                <h2>{{ 'dashboard.quick_access'|trans }}</h2>
                <div class="show-item d-flex align-items-center" data-widget-id="{{ widget_counter }}">
                    <span class="p-2 font-weight-bold">II</span>
                </div>
            </div>
            <div id="widget-{{ widget_counter }}">
                <div class="border p-2 my-2">
                    <div class="d-flex justify-content-between">
                        <span class="font-weight-bold">{{ 'dashboard.edit_account'|trans }}</span>
                        <a href="{{ path('account') }}">
                            <button>{{ 'dashboard.see'|trans }}</button>
                        </a>
                    </div>
                    <ul>
                        <li>{{ app.user.lastname }}</li>
                        <li>{{ app.user.firstname }}</li>
                        <li>{{ app.user.email }}</li>
                    </ul>
                </div>
                <div class="border p-2 my-2">
                    <div class="d-flex justify-content-between">
                        <span class="font-weight-bold">{{ 'dashboard.edit_profile'|trans }}</span>
                        <a href="{{ path('profile') }}">
                            <button>{{ 'dashboard.see'|trans }}</button>
                        </a>
                    </div>
                    <p class="mt-2 px-1">{{ app.user.skills|u.truncate(100,'...',false) }}</p>
                </div>
            </div>
        </div>
        {% set widget_counter = widget_counter + 1 %}
        <div class="col-lg border border-primary m-1">
            <div class="d-flex align-items-center justify-content-between">
                <h2>{{ 'dashboard.my_offers'|trans }}</h2>
                <div class="show-item d-flex align-items-center" data-widget-id="{{ widget_counter }}">
                    <span class="p-2 font-weight-bold">II</span>
                </div>
            </div>
            <div id="widget-{{ widget_counter }}">
                {% for offer in my_offers %}
                    {{ _self.offer_item(offer, true) }}
                {% endfor %}
            </div>
        </div>
        {% set widget_counter = widget_counter + 1 %}
        <div class="col-lg border border-primary m-1">
            <div class="d-flex align-items-center justify-content-between">
                <h2>{{ 'dashboard.my_postulated_offers'|trans }}</h2>
                <div class="show-item d-flex align-items-center" data-widget-id="{{ widget_counter }}">
                    <span class="p-2 font-weight-bold">II</span>
                </div>
            </div>
            <div id="widget-{{ widget_counter }}">
                {% for postulated_offer in my_postulated_offers %}
                    {{ _self.postulated_offer_item(postulated_offer.offer, false, postulated_offer.colorStatus) }}
                {% endfor %}
            </div>
        </div>
        {% set widget_counter = widget_counter + 1 %}
    </div>
{% endblock %}

{% macro offer_item(offer, allow_managment) %}
    <div class="border p-2 my-2{% if offer.isCancel %} opacity-75 bg-grey{% endif %}">
        <div class="d-flex justify-content-between">
            <span class="font-weight-bold">{{ offer.title }}</span>
            {% if not offer.isCancel %}
                <span class="badge badge-pill badge-{{ offer.colorStatus }}">&nbsp;</span>
            {% endif %}
        </div>
        <p>{{ offer.requiredSkills|u.truncate(150, '...', false) }}</p>
        <div class="d-flex justify-content-between">
            <div>{{ 'offer.nbApplicants'|trans({'%count%' : offer.applicants|length}) }}</div>
            <div>
                {% if allow_managment %}
                    <a href="{{ path('offre_edit', { 'id' : offer.id }) }}">
                        <button>{{ 'dashboard.edit'|trans }}</button>
                    </a>
                    {% if offer.isCancel %}
                        <a href="{{ path('offre_cancel_cancel', { 'id' : offer.id }) }}">
                            <button>{{ 'dashboard.cancel_cancel'|trans }}</button>
                        </a>
                    {% else %}
                        <a href="{{ path('offre_cancel', { 'id' : offer.id }) }}">
                            <button>{{ 'dashboard.cancel'|trans }}</button>
                        </a>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
{% endmacro %}

{% macro postulated_offer_item(offer, allow_managment, color) %}
    <div class="border p-2 my-2{% if offer.isCancel %} opacity-75 bg-grey{% endif %}">
        <div class="d-flex justify-content-between">
            <span class="font-weight-bold">{{ offer.title }}</span>
            {% if not offer.isCancel %}
                <span class="badge badge-pill badge-{{ color }}">&nbsp;</span>
            {% endif %}
        </div>
        <p>{{ offer.requiredSkills|u.truncate(150, '...', false) }}</p>
        <div class="d-flex justify-content-between align-items-center">
            <div>{{ 'offer.nbApplicants'|trans({'%count%' : offer.applicants|length}) }}</div>
            <div>
                <button type="button" class="px-3" data-toggle="modal" data-target="#offerModal-{{ offer.id }}">{{ 'dashboard.detail'|trans }}</button>
                <div class="modal fade" id="offerModal-{{ offer.id }}" tabindex="-1" aria-labelledby="offerModalLabel-{{ offer.id }}" aria-hidden="true">
                    <div class="modal-dialog modal-xl">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="offerModalLabel-{{ offer.id }}">{{ offer.title }}</h5>
                            </div>
                            <div class="modal-body">
                                <div class="d-flex justify-content-between mb-4">
                                    <div><span>{{ 'offer.linkword.looking_for_a'|trans({'%client%' : offer.client, '%profile%' : offer.profile.title|trans })|raw }}</span></div>
                                    <div><span>{{ 'offer.from'|trans({'%date%':offer.startDate|date("d/m/Y")}) }}</span></div>
                                </div>
                                <div><span>{{ 'offer.desired_technologies'|trans }} : </span><span>{{ offer.desiredTechnologies }}</span></div>
                                <div class="mt-3">
                                    <p class="h3">{{ 'offer.required_skill'|trans }}</p>
                                    <p>{{ offer.requiredSkills|nl2br }}</p>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary px-4" data-dismiss="modal">{{ 'dashboard.close'|trans }}</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endmacro %}